version: '3.3'
services:
  back:
    image: qa_test:latest
    network_mode: host
    volumes:
      - .:/app/
    ports:
        - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    command: python main.py


